### ISSUE TITLE
babel-loader.  exclude[0] must be a string/Function/RegExp

### ISSUE THREAD

**Issue by anvlkv** [webpack-contrib/thread-loader#82] opened 2019-12-04 09:33 UTC
Hi, I'm trying to use thread-loader with babel-loader but I have this error:

> ".exclude[0] must be a string/Function/RegExp."
> "Error: .exclude[0] must be a string/Function/RegExp.
>    at c:\Code\Development\Applications\node_modules\@babel\core\lib\config\validation\option-assertions.js:180:15
>    at Array.forEach (<anonymous>)
>    at assertConfigApplicableTest (c:\Code\Development\Applications\node_modules\@babel\core\lib\config\validation\option-assertions.js:178:11)
>    at c:\Code\Development\Applications\node_modules\@babel\core\lib\config\validation\options.js:107:5
>    at Array.forEach (<anonymous>)
>    at validateNested (c:\Code\Development\Applications\node_modules\@babel\core\lib\config\validation\options.js:83:21)
>    at validate (c:\Code\Development\Applications\node_modules\@babel\core\lib\config\validation\options.js:74:10)
>    at loadPrivatePartialConfig (c:\Code\Development\Applications\node_modules\@babel\core\lib\config\partial.js:66:50)
>    at Object.loadPartialConfig (c:\Code\Development\Applications\node_modules\@babel\core\lib\config\partial.js:110:18)
>    at Object.<anonymous> (c:\Code\Development\Applications\node_modules\babel-loader\lib\index.js:144:26)"

I have an exclude option set on bable-loader, but even if i comment it out I have the error.

```
threadLoader.warmup(
    {
        // pool options, like passed to loader options
        // must match loader options to boot the correct pool
        name: 'babel-pool',
        poolRespawn: !isDev
    },
    [
        'babel-loader'
        // '@babel/preset-env',
        // '@babel/preset-typescript',
        // '@babel/plugin-proposal-object-rest-spread',
        // '@babel/plugin-transform-spread',
        // '@babel/plugin-syntax-dynamic-import',
        // '@babel/plugin-proposal-decorators',
        // '@babel/plugin-proposal-class-properties'
    ]
);
{
                test: /\.(j|t)s$/,
                loaders: [
                    {
                        loader: 'thread-loader',
                        options: {
                            name: 'babel-pool',
                            poolRespawn: !isDev
                        }
                    },
                    {
                        loader: 'babel-loader',
                        options: {
                            compact: !isDev,
                            inputSourceMap: true,
                            sourceMap: true,
                            presets: [
                                '@babel/preset-env',
                                '@babel/preset-typescript'
                            ],
                            plugins: [
                                '@babel/plugin-proposal-object-rest-spread',
                                '@babel/plugin-transform-spread',
                                '@babel/plugin-syntax-dynamic-import',
                                [
                                    '@babel/plugin-proposal-decorators',
                                    {
                                        legacy: true
                                    }
                                ],
                                '@babel/plugin-proposal-class-properties'
                            ],
                            exclude: [/src[\\\/]assets[\\\/]js[\\\/].*/]
                        }
                    }
                ]
            },
```

**Comment by contra** [comment] 2020-03-03 19:40
Duplicate of #75

**Closed** 2020-06-26 16:46 UTC

**Comment by damianstone** [comment] 2022-08-24 13:56
Anyone has the solution??
