### ISSUE TITLE
File loader fails to emit files when using thread-loader on node 9

### ISSUE THREAD

**Issue by serut** [webpack-contrib/thread-loader#23] opened 2018-03-13 15:36 UTC
We've upgraded our app to node v9 and we've a new issue that prevents us to use this loader. We can reproduce that error on webpack-dev-server and webpack. Hereunder is a log from webpack that builds our app.

```
[... the webpack compilation looks fine so far]
 [393] ./src/rootRouter.js 1.71 kB {79} [built]
 [394] ./src/cdppResources.js 963 bytes {79} [built]
 [399] ./resources/logo_regards_blue_black.png 77 bytes {79} [built]
 [400] ./resources/logo_regards_blue_white.png 77 bytes {79} [built]
 [401] ./resources/logo_regards_grey_black.png 77 bytes {79} [built]
 [402] ./resources/logo_regards_grey_white.png 77 bytes {79} [built]
 [403] ./webpack-config-front/src/conf/staticConfiguration.js 206 bytes {79} [built] [failed] [1 error]
    + 1621 hidden modules

ERROR in ./webpack-config-front/src/conf/staticConfiguration.js
Module build failed: Thread Loader (Worker 3)
File Loader
emitFile is required from module system
    at Object.loader (/app_to_build/node_modules/file-loader/dist/index.js:28:29)
 @ ./src/main.jsx 59:2-74
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```
https://github.com/webpack-contrib/file-loader/blob/e73131fe1986cf930058e8f0868872a4a91d5f31/src/index.js#L10

If I evaluate in the console `this.emitFile`, it prints the real function several times but one time I get an undefined.

Our webpack rules (nothing special so far):
```
     {
          test: /\.jsx?$/, 
          // Exclude the DLL folder build from the transpilation 
          exclude: [/node_modules/, /dist/], 
          use: [ 
            'thread-loader', 
            'babel-loader?cacheDirectory', 
          ]
     },
     {
          test: /staticConfiguration(\.dev)?\.js$/,
          loader: 'file-loader',
          options: {
            name: 'staticConfiguration.js',
            outputPath: 'conf/',
          },
      },
````
When we stop using `thread-loader` the error disappear. **And with node v6 or v7 there is no issue.**

```
$ npm -v
5.8.0-next.0
$ node -v
v9.8.0
$ cat package.json
    "webpack": "3.11.0",
    "webpack-dev-server": "~2.11.0",
    "file-loader": "1.1.10",
    "thread-loader": "^1.1.5",
```

**Comment by evilebottnawi** [comment] 2018-03-13 15:52
@serut can you create minimum reproducible test repo?

**Comment by serut** [comment] 2018-03-13 17:32
I'm working behind a proxy, so I can't publish easily to github. Hopefully this is straightforward : 

`index.jsx`
```
require('./staticConfiguration')
```

`package.json`
```
{
  "name": "test-repro-thread-loader",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build:production": "webpack --progress --config webpack.config.js --display-error-details"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "thread-loader": "^1.1.5",
    "file-loader": "1.1.10",
    "webpack": "3.11.0",
    "babel-cli": "~6.26.0",
    "babel-core": "~6.26.0",
    "babel-eslint": "~8.2.2",
    "babel-loader": "~7.1.4",
    "babel-register": "~6.26.0",
    "babel-runtime": "~6.26.0"
  }
}
```

`staticConfiguration.js`
```
const a = 'b'
```

`webpack.config.js`
```
const webpack = require('webpack')
const threadLoader = require('thread-loader')

threadLoader.warmup({}, ['babel-loader'])

module.exports = {
    output: {
      // Webpack compilation directory
      path: `${__dirname}/dist/prod`,
      // Webpack main bundle file name
      filename: 'bundle.js',
      publicPath: '/',
    },
	// Javascript main entry
	entry: './index.jsx',
	node: {
	  net: 'empty',
	  tls: 'empty',
	  dns: 'empty',
	},
	resolve: {
	  // Automaticaly get extensions files from javascript code with import or require.
	  // exemple require('main') look for main, main.js or main.jsx with our configuration
	  extensions: ['.js', '.jsx'],
	},
	module: {
	  rules: [
	    // Transpile ES6 Javascript into ES5 with babel loader
	    {
	      test: /\.jsx?$/,
	      exclude: [/node_modules/, /dist/],
	      use: [
	        'thread-loader',
	        'babel-loader',
	      ],
	    },
	    {
          test: /staticConfiguration(\.dev)?\.js$/,
          loader: 'file-loader',
          options: {
            name: 'staticConfiguration.js',
            outputPath: 'conf/',
          },
	    },
	  ],
	},
}
```



Stacktrace: 
```
$ npm run build:production
Hash: edb0d09a4d40469d91ba                                                         
Version: webpack 3.11.0
Time: 575ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.81 kB       0  [emitted]  main
   [0] ./index.jsx 33 bytes {0} [built]
   [1] ./staticConfiguration.js 235 bytes {0} [built] [failed] [1 error]

ERROR in ./staticConfiguration.js
Module build failed: Thread Loader (Worker 0)
File Loader

emitFile is required from module system


```

**Comment by michael-ciniawsky** [comment] 2018-03-13 17:54
Could you try excluding `staticConfiguration`  from the 'JSX'  rule ?

**Comment by michael-ciniawsky** [comment] 2018-03-13 18:03
I can't reproduce the `{Error}`, but if I explicitly declare the files I want to be copied by the `file-loader` it works. The `{Error}` is to be expected when using the `thread-loader` since File I/O isn't available in 'workers'.

![static](https://user-images.githubusercontent.com/5419992/37360653-2c62a754-26f1-11e8-9d9b-cd208ba12c00.png)

**Comment by serut** [comment] 2018-03-13 18:42
> Could you try excluding `staticConfiguration` from the 'JSX' rule ?

Yeah yeah I can reverse the order between these two rules and retry. It may works as the file will not be catched anymore by `thread-loader`.

> I can't reproduce the `{Error}`

Hmm, strange, it's easily reproduceable on my computer. Are you using npm & node latest versions ?

**Comment by michael-ciniawsky** [comment] 2018-03-13 18:54
> Yeah yeah I can reverse the order between these two rules and retry. It may works as the file will not be catched anymore by thread-loader.

Any loader that relies on File I/O (`this.emitFile`) (like e.g `file-loader`) will simply not work with `thread-loader`, it's not a bug...

> Hmm, strange, it's easily reproduceable on my computer. Are you using npm & node latest versions ?

What I exactly meant is getting two similar rules like yours merged to produce the same `{Error}`. If I  declare one rule with `thread-loader!file-loader./file.js` it fails.

Anyways you will need to refactor your config :)

**Closed by michael-ciniawsky** 2018-03-13 18:54 UTC
Labels: flag: Needs more info

**Comment by serut** [comment] 2018-03-13 19:00
Sounds good to me. Something changed with node 9 but we'll never know (maybe that's better ? 😄)

Thanks for the clue.
